### ISSUE TITLE
Missing Hunger/Thirst Bar after getting killed

### ISSUE THREAD

**Issue by eysikun** [TazLTD/ltd-hud#1]
![image](https://github.com/user-attachments/assets/2ea48a31-c027-44b0-8566-da64fa40146b)

**Comment by TazLTD** [comment]
I'll look into that

**Comment by TazLTD** [comment]
They appear at 
99% hunger 
99% thirst
1% stress
When your hunger and thirst are full or when you have no stress, the bars are hidden
